<?php

define('CONSUMER_KEY',"YOUR APP'S CONSUMER KEY");
define('CONSUMER_SECRET',"YOUR APP'S CONSUMER SECRET");

/*

define('CONSUMER_KEY',"H");
define('CONSUMER_SECRET',"YOUR APP'S CONSUMER SECRET");

*/